export const sliderItems = [
  {
    id: 1,
    img: "https://images.unsplash.com/photo-1612541122840-bf7071c968a2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fHdoaXRlJTIwc2hpcnR8ZW58MHx8MHx8fDA%3D&w=1000&q=80",
    title: "SUMMER SALE",
    desc: "DON'T SKIMP ON STYLE! GET FLAT 30% DISCOUNT FOR NEW ARRIVALS.",
    bg: "#f8f8f8",
  },
  {
    id: 2,
    img: "https://www.forever21.com/dw/image/v2/BFKH_PRD/on/demandware.static/-/Sites-f21-master-catalog/default/dwbbd807d4/1_front_750/00478486-03.jpg?sw=300&sh=450",
    title: "AUTUMN COLLECTION",
    desc: "DON'T SKIMP ON STYLE! GET FLAT 30% DISCOUNT FOR NEW ARRIVALS.",
    bg: "#e9e9e9",
  },
  {
    id: 3,
    img: "https://cdn.shopify.com/s/files/1/0184/5074/3360/products/CK-2001-02A_1024x1024.jpg?v=1618219879",
    title: "WINTER COLLECTION",
    desc: "DON'T SKIMP ON STYLE! GET FLAT 30% DISCOUNT FOR NEW ARRIVALS.",
    bg: "#ebc0ac",
  },
];
export const products = [
  {
    id: 1,
    img: "https://shop.adarbepari.com/wp-content/uploads/2021/04/bangladesh-flag-cotton-tshirt.jpg",
    color: "green",
    size: "X",
    price: "$10",
  },
  {
    id: 2,
    img: "https://render.fineartamerica.com/images/rendered/default/t-shirt/23/25/images/artworkimages/medium/1/team-work-makes-the-dream-work-motivational-quote-quote-design-transparent.png?targetx=28&targety=-1&imagewidth=371&imageheight=575&modelwidth=430&modelheight=575",
    color: "grey",
    size: "XL",
    price: "$12",
  },
  {
    id: 3,
    img: "https://5.imimg.com/data5/ECOM/Default/2023/4/301888499/IZ/LW/IC/7224153/front-643fde94dae9c-dusty-rose-s-oversized-t-shirt-250x250.jpg",
    color: "pink",
    size: "S",
    price: "$10",
  },
  {
    id: 4,
    img: "https://png.pngitem.com/pimgs/s/38-386945_cargo-pants-khaki-pocket-cargo-pants-transparent-background.png",
    color: "brown",
    size: "M",
    price: "$20",
  },
  {
    id: 5,
    img: "https://m.media-amazon.com/images/I/51CRoQryqnL._AC_.jpg",
    color: "purple",
    size: "L",
    price: "$30",
  },
  {
    id: 6,
    img: "https://media.karousell.com/media/photos/products/2022/8/15/ready_stock_in_malaysia__baile_1660562484_1ee628fb_progressive.jpg",
    color: "black",
    size: "XS",
    price: "$25",
  },
  {
    id: 7,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFk7QC5KNUjGq6IqRPj4a9AmcyLM2AY_K0dA&usqp=CAU",
    color: "black",
    size: "X",
    price: "$15",
  },
  {
    id: 8,
    img: "https://images.vans.com/is/image/VansEU/VN0A3WMAVNE-HERO?$PDP-FULL-IMAGE$",
    color: "black",
    size: "X",
    price: "$80",
  },
];
